project:
  type: book
  output-dir: ../../../../test_pdf_local/
  render:
    - index.qmd
    - 01-part-A.qmd
    - 02-part-B.qmd
    - 03-appendix.qmd
editor:
  markdown:
    references:
      location: block
      prefix: "Main_Analysis_"

format: 
  pdf:
    fontfamily: libertinus  # Modern, readable
    # or
    # fontfamily: lmodern   # Latin Modern (default LaTeX)
    # or  
    # fontfamily: palatino  # Palatino-like
    fontsize: 10pt
    code-line-numbers: false
    papersize: a4
    geometry:
      - top=2cm
      - bottom=2cm
      - left=2.5cm
      - right=2cm
    linestretch: 1.15
    toc: true
    toc-depth: 5
    toc-title: Contents
    highlight-style: arrow

book:
  title: "Target Discovery Report"
  author: "Stefan Boeing"
  chapters:
    - index.qmd
    - 01-part-A.qmd
    - 02-part-B.qmd
    - 03-appendix.qmd