project:
  type: book
  output-dir: ../../../../output_pdf/
  render:
    - index.qmd
    - 02-partA.qmd
    - 03-partB.qmd
    - 04-appendix.qmd
    - 01-introduction.qmd
    - 02-python-to-r.qmd
    - 03-r-to-python.qmd
    - 04-summary.qmd
    - 05-figures.qmd

editor:
  markdown:
    references:
      location: block
      prefix: "Main_Analysis_"

format: 
  pdf:
    fontfamily: libertinus  # Modern, readable
    # or
    # fontfamily: lmodern   # Latin Modern (default LaTeX)
    # or  
    # fontfamily: palatino  # Palatino-like
    fontsize: 10pt
    code-line-numbers: false
    papersize: a4
    geometry:
      - top=2cm
      - bottom=2cm
      - left=2.5cm
      - right=2cm
    linestretch: 1.15
    toc: true
    toc-depth: 5
    toc-title: Contents
    highlight-style: arrow
    

book:
  title: "Drug Target Evaluation Report"
  author: "Stefan Boeing"
  chapters:
    - index.qmd
    - 02-partA.qmd
    - 03-partB.qmd
    - 04-appendix.qmd
    - 01-introduction.qmd
    - 02-python-to-r.qmd
    - 03-r-to-python.qmd
    - 04-summary.qmd
    - 05-figures.qmd